name: Print Modified Files

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  print_modified_files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get changed files
        id: getfile
        run: |
          echo "::set-output name=files::$(git diff --name-only ${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.head.sha }})"
          
      - name: Print changed files
        run: |
          echo "Modified files in this PR:"
          echo "${{ steps.getfile.outputs.files }}"